#! /bin/sh

readonly progName='hct'
readonly helpHint="Try '$progName --help' for more information."
readonly helpText="Usage: $progName [-h][--help] | [command]
Get information about Chinese characters.

Options:
  -h, --help    show this text help and exit

Available commands:
  composition
  components
  readings
  variants"

# Get the script's source dir.
SOURCE_DIR=$(dirname -- "$(readlink -f "$0")")

# Process the comand line arguments
if [[ -z $1 || $1 == -h || $1 == --help ]]; then
    echo "$helpText"
    exit 0
else
    if [[ $1 == composition || $1 == components || $1 == reading || $1 == variants ]]; then
        exec $SOURCE_DIR/lib/hct-$1.sh "${@:2}"
    else
        echo "$progName: invalid command '$1'" >&2
        echo "Try '$progName --help' for more information." >&2
        exit 1
    fi
fi
