.TH HCT-READING 1 "Version 0.9"
.
.SH NAME
hct\-reading \- get the reading (pronunciation) of Han characters,
aka Chinese characters, in different languages
.
.SH SYNOPSIS
.B hct reading
.RB [ \-h ]
.RB [ \-\-help ]
.br
.B hct reading
.RB [ \-V ]
.RB [ \-\-version ]
.br
.B hct reading
.RB [ \-q ]
.I INPUT
.PP
(See the
.B OPTIONS
section for alternative long option names)
.
.SH DESCRIPTION
.B hct\-reading
is a tool to retrieve pronunciation information, aka the reading, of a given
Han character in different languages and language systems.
.PP
Han characters are normally associated with Chinese language,
however, Chinese is not the only language that uses them.
.br
.B hct\-reading
can provide a reading for the following languages and language systems:
Cantonese, Japanese, Japanese-Kun, Japanese-On, Korean, Mandarin and Vietnamese.
.PP
A character or a list of characters must be given as an input.
.TP
\fIINPUT\fR shall be one of the following:
A single Han character,
.br
A file containing a list of single Han characters separated by newlines, or
.br
A single hyphen '\-', in which case the input is read from the stdin stream.
.PP
The queried reading will be printed to the stdout stream,
and it will be formatted according to the input type.
.TP
Output when a single character is given as an input:
Print the queried reading for the given character to the stdout stream.
.br
If an error is encountered for the given character, print an explanatory
error message to the stderr stream.
.TP
Output when a list of characters is given as an input:
For each of the listed characters, print the given character and the queried
reading separated by a single tab character to the stdout stream.
.br
If an error is encountered for any of the listed characters, print the given
character and the error code separated by a single tab character to the
stdout stream.
.br
Additionally, if the stdout stream is not going to a terminal, for instance
when piping it to a file, a brief summary of the used options is included in
the output.
.br
Finally, a progress status message is also shown at the bottom of the
resulting character list as it processes.
The progress status is printed to the stderr stream.
.
.SH OPTIONS
.TP
.B \-\-cantonese
Retrieve the Cantonese reading for the given input.
.TP
.B \-\-japanese
Retrieve the Japanese reading for the given input.
.TP
.B \-\-japanese-kun
Retrieve the Japanese-Kun reading for the given input.
.TP
.B \-\-japanese-on
Retrieve the Japanese-On reading for the given input.
.TP
.B \-\-korean
Retrieve the Korean reading for the given input.
.TP
.B \-\-mandarin
Retrieve the Mandarin reading for the given input.
.TP
.B \-\-vietnamese
Retrieve the Vietnamese reading for the given input.
.IP
When multiple language options are specified, only the last given
option is considered.
.br
If no language option is specified, a Mandarin reading is retrieved.
.TP
.BR \-q , \ \-\-quiet
Suppress error messages from the stderr stream.
.TP
.BR \-V , \ \-\-version
Show version information and exit.
.TP
.BR \-h , \ \-\-help
Show the help message and exit.
.
.SH EXIT STATUS
.TP
.B 0
Character or file processed correctly.
.TP
.B 1
An invalid command line option was given.
.TP
.B 3
An invalid input was given.
.TP
.B 4
One of the internal database files was not found.
.TP
.B 10
The given string has more than one character.
.TP
.B 20
The given character is not present in the IDS database.
.TP
.B 21
The given character is not present in the Readings database.
.TP
.B 22
The given character has no reading information for the selected language.
.
.SH EXAMPLES
.TP
.BR "hct reading" \ 和
Print the Mandarin reading of 和.
.TP
.BR "hct reading" \ 25-chars.txt \ \-\-cantonese
Print the Cantonese reading of all the characters in the specified file.
.TP
.RB "tail \-n5 100-chars.txt | " "hct reading" " \- " \-\-korean
Print the korean reading of 5 characters, which are piped from the
.B tail -n5
command.
.TP
.RB "head -n100 5000-chars.txt | " "hct reading" " \- > 100-chars-reading.txt"
Print the Mandarin reading of 100 characters, which are piped from the
.B head -n100
command, and pipe the output into the specified file.
.
.SH SEE ALSO
.BR hct-composition(1) ,
.BR hct-components(1) ,
.BR hct-definition(1) ,
.BR hct-variants(1)
.
.SH BUGS
Bugs can be reported and filed at
https://github.com/omulh/HanCharTools/issues
